### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by andypotanin** [wp-property/wp-avalon#1]
![image](https://cloud.githubusercontent.com/assets/1255935/14076000/bff693f2-f4e6-11e5-8e5e-3ac581083b5a.png)

**Comment by Mashenka** [comment]
- [x] Выпадающее меню с треуголничком сверху + убрать лишнее пространство возле первого и последниего item 
  ![image](https://cloud.githubusercontent.com/assets/5111163/14182132/aa1ce2fa-f772-11e5-8743-727a3ddbf0ae.png)
  - [x] Footer
    ![image](https://cloud.githubusercontent.com/assets/5111163/14182300/5208f6fc-f773-11e5-8b7b-2110889094b3.png)
- [x] Этот блок должен добавляться как виджет area на Home page и Properties page. Туда можно будет добавлять разные виджеты в том числе и Property search. Каждый новый виджет добавляет новую вкладку.
  ![image](https://cloud.githubusercontent.com/assets/5111163/14182495/118885f6-f774-11e5-93f9-f9a6f9492ed7.png)
