### ISSUE TITLE
Post

### ISSUE THREAD

**Issue by andypotanin** [wp-property/wp-avalon#10]
![image](https://cloud.githubusercontent.com/assets/1255935/14076099/612acff4-f4e7-11e5-8b1d-e35832905d96.png)

**Comment by Mashenka** [comment]
- [x] View of the Post comment need to be changed

https://avalon.workspace.uds.io/my-charming-post/

**Comment by SoSeductive** [comment]
![fireshot screen capture 034](https://cloud.githubusercontent.com/assets/2156026/16840377/0ada2e1a-49dd-11e6-9fae-d4ae3cf49566.png)

**Comment by SoSeductive** [comment]
480px width devices - http://joxi.ru/82QbpBh1xXNYAd
640 - http://joxi.ru/KAx3dBi45xDb28
1200 - http://joxi.ru/KAx3dBi45xDb28
