### ISSUE TITLE
Login Register

### ISSUE THREAD

**Issue by andypotanin** [wp-property/wp-avalon#13]
![image](https://cloud.githubusercontent.com/assets/1255935/14076168/08805706-f4e8-11e5-8241-603dbba50d9c.png)

**Comment by Mashenka** [comment]
when tried to register, can't get the password

![image](https://cloud.githubusercontent.com/assets/5111163/16803108/2d916b38-490d-11e6-9f93-c6b3c26a20ce.png)

Username: test To set your password, visit the following address: https://avalon.workspace.uds.io/wp-login.php

**Comment by SoSeductive** [comment]
@andypotanin Maybe you can help? I Did some fixes for "Password reset" message. This message i can  change with add_filter, but when user register, message send another function - wp_new_user_notification(). Message in this function we cant change with theme functions ( i cant find answer )

This is screenshot of message which send avalon.workspace.uds.io
![bmo56efm4ljgay](https://cloud.githubusercontent.com/assets/2156026/16833704/1dde4312-49b9-11e6-926a-2d9c44b83002.png)

And this is from another site 
![lmgbq9hr08azrl](https://cloud.githubusercontent.com/assets/2156026/16833761/546c05ae-49b9-11e6-99d9-603d885e9c9c.png)

avalon.workspace.uds.io dont send set password link

**Comment by andypotanin** [comment]
Hm it must take siteurl/home from DB while we override it as a constant. Try updating home and siteurl in wp-admin/options.php directly.

**Comment by SoSeductive** [comment]
it is not need to updating home and siteurl. devs.company - it is my site. i just testing avalon theme and registration messages

**Comment by andypotanin** [comment]
Okay then I misunderstood the problem. We're just trying to change the message? If so, why? Why not leave the message as-is and let plugins deal with custom messages if a user really needs that, I don't see it being the responsibility of the theme to modify the contents of the emails.

**Comment by SoSeductive** [comment]
We need to change message becouse defaul message has < before and > after link (like this - http://permalink/ ), and workspace server send message without link, becouse, i think, workspace server think what it is a html tag... I think ploblem in workspace server. If User download Avalon theme and he has similar server, he will have the same problem

**Comment by Mashenka** [comment]
@andypotanin Issue with workspace's server, that it eats required link, because it contains <>. On other servers works. So probably there should be some option which should be enabled/disabled on the server. Probably we have some option which is responsible for security. I just wanted to know it's name in case I will need to suggest something to users.

I will close this task, cause this is not related to theme.
