### ISSUE TITLE
Different styles for buttons

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-avalon#23]
this is feps menu registration form ( in others themes password reset is a link)
![image](https://cloud.githubusercontent.com/assets/5111163/16683860/9415f7ea-450a-11e6-949b-da9ca591e432.png)

![image](https://cloud.githubusercontent.com/assets/5111163/16683951/f518b410-450a-11e6-82a1-1f69b22cead0.png)

this is wordpress registration form(another blue color for register button and no reset password on log in form)
![image](https://cloud.githubusercontent.com/assets/5111163/16683909/c9cddba0-450a-11e6-9db6-0a2898479d28.png)

**Comment by SoSeductive** [comment]
![fireshot screen capture 033](https://cloud.githubusercontent.com/assets/2156026/16833448/13166bcc-49b8-11e6-99d2-91aee4cb1d82.png)
