### ISSUE TITLE
Add options to set up Search on Home page

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-avalon#27]
There should be something like this
![image](https://cloud.githubusercontent.com/assets/5111163/18507520/56666142-7a79-11e6-9426-f8a8f5bdaf25.png)

![image](https://cloud.githubusercontent.com/assets/5111163/17888514/fda106da-6933-11e6-820e-2f0cf5945b3b.png)

**Comment by SoSeductive** [comment]
![nayolvcxpb9lmz](https://cloud.githubusercontent.com/assets/2156026/18919226/023eb1ea-85a6-11e6-9141-2a26e40b9d84.png)

**Comment by Mashenka** [comment]
Notice: Undefined index: in /var/www/wp-content/themes/wp-avalon/functions.php on line 713
Notice: Undefined index: in /var/www/wp-content/plugins/wp-property/lib/template-functions.php on line 1152

**Comment by SoSeductive** [comment]
Fixed notices in Avalon, like - Undefined index: in /var/www/wp-content/themes/wp-avalon/functions.php
but this - Notice: Undefined index: in /var/www/wp-content/plugins/wp-property/lib/template-functions.php is bug of property

**Comment by Mashenka** [comment]
Change text for Home Search settings
