### ISSUE TITLE
Properyt overview image sizes

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-avalon#29]
images should be cropped to one size to prevent such issues
![image](https://cloud.githubusercontent.com/assets/5111163/18099105/ab0a3f58-6eed-11e6-9b02-a8772169ee0f.png)

example from user's site
https://squarefeet.ca/

**Comment by Mashenka** [comment]
Still do not see on Avalon - https://avalon.workspace.uds.io/properties/

**Comment by SoSeductive** [comment]
I am add new image - http://joxi.ru/MAjg7EuvzNoKre.png
And reload page - http://joxi.ru/n2YlRgSjMWyzm6.png

**Comment by Mashenka** [comment]
https://avalon.workspace.uds.io/properties/

![image](https://cloud.githubusercontent.com/assets/5111163/19810017/6616f7e0-9d34-11e6-8865-b3d37e0172f3.png)
