### ISSUE TITLE
Incorrect Spelling 

### ISSUE THREAD

**Issue by ElenaRad** [wp-property/wp-avalon#31]
Incorrect spelling in Welcome. 
![image](https://cloud.githubusercontent.com/assets/19193013/18347405/fa2db70e-75cd-11e6-82ef-8640440ee16d.png)

thank you!

**Comment by ElenaRad** [comment]
Not sure why but when uploading the latest branch, I still get the wrong spelling on the Cover page of Avalon: 
![image](https://cloud.githubusercontent.com/assets/19193013/24368478/3d2c5008-1329-11e7-96f6-11b4eec1e03c.png)

**Comment by SoSeductive** [comment]
@Mashenka ^ I did it 5th April
