### ISSUE TITLE
Add ability to Insirt links to the Avalon widgets

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-avalon#33]
![image](https://cloud.githubusercontent.com/assets/5111163/18959408/b73b1020-866e-11e6-86e8-05a1d42278a4.png)

**Comment by SoSeductive** [comment]
for add link in widget need write HTML http://joxi.ru/DmBw18hN0KBv2P.png
<a href='Link'>Href</a> Link need embed with single brackets
