### ISSUE TITLE
Comment styles

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-avalon#37]
![image](https://cloud.githubusercontent.com/assets/5111163/19859499/1b765ecc-9f8e-11e6-9283-9c7d507333b0.png)

**Comment by SoSeductive** [comment]
https://workspace.uds.io/properties/1800-440-olohana-street-pending-image-downloads/
![3a6ea76e38](https://cloud.githubusercontent.com/assets/2156026/22243157/cd62f1bc-e22e-11e6-8501-79a230738115.png)
