### ISSUE TITLE
Need to exclude shortcodes from map details box

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-avalon#41]
![image](https://cloud.githubusercontent.com/assets/5111163/21728286/0b7a8f58-d44e-11e6-9616-8c9ead2acef8.png)

**Comment by SoSeductive** [comment]
I think it is problem not avalon theme.

**Comment by Mashenka** [comment]
Ok. Created task in wp-property  - https://github.com/wp-property/wp-property/issues/381

**Comment by SoSeductive** [comment]
Sorry, it is real avalons problem

**Comment by SoSeductive** [comment]
all is done
