### ISSUE TITLE
Notice

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-avalon#42]
Notice: Undefined index: sort_stats_by_groups in /var/www/wp-content/themes/wp-avalon/template-parts/content/content-property.php on line 92

![image](https://cloud.githubusercontent.com/assets/5111163/21934101/da3ec7ca-d9b0-11e6-9135-f03583098e76.png)

https://workspace.uds.io/properties/1800-440-olohana-street-pending-image-downloads/

**Comment by SoSeductive** [comment]
@Mashenka Notice is disappeared. Maybe something changed in settings?

**Comment by Mashenka** [comment]
I still saw it yesterday on workspace. On avalon probably not latest versions of products
