### ISSUE TITLE
add color set up for background 

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-avalon#47]
![image](https://cloud.githubusercontent.com/assets/5111163/25281135/1268bd9e-26b5-11e7-9545-5f92203bf315.png)

**Comment by Mashenka** [comment]
can you make screenshot where did you add?

**Comment by SoSeductive** [comment]
![avalon_bg_color](https://cloud.githubusercontent.com/assets/2156026/25285167/fc0b0374-26c1-11e7-92b6-4fcb1b602e28.png)
