### ISSUE TITLE
color option

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-avalon#48]
color option for that text

![image](https://cloud.githubusercontent.com/assets/5111163/25800332/86db551c-33f1-11e7-891a-7931301db84c.png)

**Comment by SoSeductive** [comment]
@Mashenka I replace background color of footer and labels here and create text color changer
![4f35463d0e](https://user-images.githubusercontent.com/2156026/32450408-cd094688-c31c-11e7-8f07-bf5a105d0a57.png)
