### ISSUE TITLE
odd Page title when enabling content on Home page

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-avalon#53]
![image](https://user-images.githubusercontent.com/5111163/27490359-a41fb9dc-5846-11e7-903e-d704a8ee9174.png)

![image](https://user-images.githubusercontent.com/5111163/27490376-b77a3566-5846-11e7-9fcd-e688d6c5ec3f.png)

**Comment by SoSeductive** [comment]
@Mashenka This is just home page title

**Comment by Mashenka** [comment]
@SoSeductive yes, just when you need content but do not need that title what to do?

**Comment by SoSeductive** [comment]
oh. i am get it..
