### ISSUE TITLE
property overview widget styles

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-avalon#57]
it is displaying in full width,  good for sidebars, but e.g for more than 300 width need to show like shortcode

how it looks now
https://demo.usabilitydynamics.com/avalon/page-builder-page/
![image](https://user-images.githubusercontent.com/5111163/30398345-b5f7c122-98d8-11e7-880b-c6575cfad8db.png)

how it can be
![image](https://user-images.githubusercontent.com/5111163/30398386-d95b9896-98d8-11e7-9395-68744b89fa89.png)

**Comment by SoSeductive** [comment]
@Mashenka Done and commited

**Comment by Mashenka** [comment]
still same look https://demo.usabilitydynamics.com/avalon/page-builder-page/
