### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-avalon#59]
@andypotanin do we need to add a license option? How will users know about the updates?

**Comment by andypotanin** [comment]
@Mashenka Yes, have @SoSeductive add it like it is in other themes.

**Comment by SoSeductive** [comment]
@Mashenka @andypotanin Added license to WP Avalon

**Comment by Mashenka** [comment]
Can I check on demo/avalon? where are commits?

**Comment by Mashenka** [comment]
@SoSeductive why did you put suggestion notice for Jetpack? Avalon does not suggest it as I know.
