### ISSUE TITLE
Copy and style Favorite and Compare widgets from Madison theme

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-avalon#66]

**Comment by SoSeductive** [comment]
* Added Favorites and Compare functionality
* Setting in customizer, including colors for BG and fonts (for Favorites and for Compare - different settings)
* Mobile styles (Only not > 460px, because i don't know how we should do comparing in small windowses)

**Comment by SoSeductive** [comment]
Also, transferred `FontAwesome` icons and styles

**Comment by Mashenka** [comment]
where are icons on overview?
https://workspace.uds.io/properties/?wpp_search%5Bpagination%5D=off&wpp_search%5Bstrict_search%5D=false&wpp_search%5Bproperty_type%5D=building%2Cfloorplan%2Csingle_family_home%2Capartmenttownhome%2Cinactive_single_family_home%2Cinactive_apartment%2Ccommercial_property%2Ccommercial_unit&wpp_search%5Bwpml_test%5D=-1&wpp_search%5Btest%5D=-1&wpp_search%5Battr_with_slashes%5D=-1&wpp_search%5Bprice%5D%5Bmin%5D=-1

![image](https://user-images.githubusercontent.com/5111163/39768476-105d8d8a-52f2-11e8-80fe-b86d137b8763.png)

**Comment by Mashenka** [comment]
when clicking compare, some mess
https://workspace.uds.io/properties/test-property/

![image](https://user-images.githubusercontent.com/5111163/39769495-0d0f4300-52f5-11e8-9f2e-ce8d3e9e0502.png)

**Comment by SoSeductive** [comment]
@Mashenka Done. [test it please](https://workspace.uds.io/properties/?wpp_search%5Bpagination%5D=off&wpp_search%5Bstrict_search%5D=false&wpp_search%5Bproperty_type%5D=building%2Cfloorplan%2Csingle_family_home%2Capartmenttownhome%2Cinactive_single_family_home%2Cinactive_apartment%2Ccommercial_property%2Ccommercial_unit&wpp_search%5Bwpml_test%5D=-1&wpp_search%5Btest%5D=-1&wpp_search%5Battr_with_slashes%5D=-1&wpp_search%5Bprice%5D%5Bmin%5D=-1)

**Comment by Mashenka** [comment]
where is plus symbol? - 
![image](https://user-images.githubusercontent.com/5111163/40763603-11f3fdbe-64ae-11e8-8886-c3fd93d97cc2.png)

checkboxes not showing
![image](https://user-images.githubusercontent.com/5111163/40764380-79b76942-64b1-11e8-9cc7-6d3c8d07fcbe.png)

![image](https://user-images.githubusercontent.com/5111163/40764475-d5a4e8e2-64b1-11e8-9efa-91f41d650ccb.png)

some undefined variables(in Madison also)
![image](https://user-images.githubusercontent.com/5111163/40764364-65bc3eae-64b1-11e8-883a-b51565b93eef.png)

**Comment by SoSeductive** [comment]
@Mashenka 
- [x] - Add a "plus" symbol
- [x] - Fix checkboxes 
- [x] - Some undefined variables (if you add property in Favorites and then delete property - you can see undefined variables)

**Comment by SoSeductive** [comment]
@Mashenka Why reopened ?
