### ISSUE TITLE
Warning in Appearence->Customize tab

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-avalon#69]
when I go to Appearence->Customize and try to change the frontpage widgets titles, Warning: mysqli_set_charset(): Error executing query in /hermes/bosnaweb17a/b743/ipg.epixelmediacom/gites/wp-includes/wp-db.php on line 756 Warning: Cannot modify header information - headers already sent by (output started at /hermes/bosnaweb17a/b743/ipg.epixelmediacom/gites/wp-includes/wp-db.php:756) in /hermes/bosnaweb17a/b743/ipg.epixelmediacom/gites/wp-includes/pluggable.php on line 1216

**Comment by SoSeductive** [comment]
@Mashenka I can't repeat this issue
