### ISSUE TITLE
Agents

### ISSUE THREAD

**Issue by andypotanin** [wp-property/wp-avalon#7]
![image](https://cloud.githubusercontent.com/assets/1255935/14076081/419f3d14-f4e7-11e5-8dc2-791f679e10a5.png)

**Comment by Mashenka** [comment]
can you add number of listings to the existing agent card - https://avalon.workspace.uds.io/ag/

![image](https://cloud.githubusercontent.com/assets/5111163/16802502/9a258580-4909-11e6-8cb5-d16a97ae56f1.png)

and remove odd space under content - 
![image](https://cloud.githubusercontent.com/assets/5111163/16802469/7421f7c4-4909-11e6-8b1e-76717fe25fc0.png)

**Comment by SoSeductive** [comment]
wp-propety-agents plugin does not allow do this
