### ISSUE TITLE
Favorite and Compare disable option not working

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-avalon#72]
![image](https://user-images.githubusercontent.com/5111163/48776883-bdbae280-ecd9-11e8-822b-4690ac96244f.png)

**Comment by SoSeductive** [comment]
@Mashenka Fixed

**Comment by Mashenka** [comment]
this functiomality should be also hidden
![image](https://user-images.githubusercontent.com/5111163/56131455-1e500200-5f90-11e9-906f-d637a475eb51.png)

icons on single page is hiding correctly now

**Comment by SoSeductive** [comment]
@Mashenka Done
