### ISSUE TITLE
multi-check box and radio attributes not styles in feps form

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-avalon#75]
https://udx-ci-develop-maria.rabbit.ci/feps/
default theme
![image](https://user-images.githubusercontent.com/5111163/55191671-770b5680-51ab-11e9-9f13-2ad392787b44.png)
Avalon
![image](https://user-images.githubusercontent.com/5111163/55191742-a15d1400-51ab-11e9-9ec5-b8ee434df211.png)

**Comment by SoSeductive** [comment]
@Mashenka Done
