### ISSUE TITLE
All Button color settings not working

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-avalon#76]
it is changing in customizer for a while and after settings are published nothing changed on real site - 
![image](https://user-images.githubusercontent.com/5111163/56113210-dcaa6180-5f65-11e9-8c22-b258c54eea6a.png)

**Comment by SoSeductive** [comment]
@Mashenka I use 'latest' branch
![img](https://user-images.githubusercontent.com/2156026/56116056-83463080-5f6d-11e9-9cd2-804066af8566.png)

**Comment by SoSeductive** [comment]
@Mashenka Done
