### ISSUE TITLE
Name of the group should with capital letter

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-avalon#77]
![image](https://user-images.githubusercontent.com/5111163/56131825-396f4180-5f91-11e9-9490-766e53a97388.png)

![image](https://user-images.githubusercontent.com/5111163/56131904-63286880-5f91-11e9-9236-9d40982615d7.png)

https://udx-ci-develop-maria.rabbit.ci/properties/property-2/

**Comment by SoSeductive** [comment]
@Mashenka Done

**Comment by Mashenka** [comment]
still the same

**Comment by Mashenka** [comment]
ok, that was cache
