### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by andypotanin** [wp-property/wp-avalon#9]
![image](https://cloud.githubusercontent.com/assets/1255935/14076094/57126cde-f4e7-11e5-988b-e60b58d772ae.png)

**Comment by Mashenka** [comment]
https://avalon.workspace.uds.io/blog/
- [x] Number of comments not displaying
- [x] Comments not displaying under the posts
- [x] When image is not big text not aligned ti the rightr
- [x] Learn More button need to be added
- [x] Make pagination centered and on the top of the page also
